name: bkk_drugstore_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  provider: ^6.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.2.0
  http: ^1.2.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  auto_size_text: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Light.ttf
          weight: 300
        - asset: assets/fonts/Prompt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Prompt-SemiBold.ttf
          weight: 600